### ISSUE TITLE
cannot import name 'CallbackList' from 'keras.callbacks'

### ISSUE THREAD

**Issue by Gaethje** [pocokhc/agent57#1]
I am trying to run mountaincar.py
after installing the packages mentioned，i am facing this import error.

(agent57) $ python mountaincar.py
Traceback (most recent call last):
  File "mountaincar.py", line 10, in <module>
    from agent.agent57 import ActorUser
  File "../agent/agent57.py", line 3, in <module>
    import rl.core
  File "/home/initial/miniconda3/envs/agent57/lib/python3.7/site-packages/rl/core.py", line 8, in <module>
    from rl.callbacks import (
  File "/home/initial/miniconda3/envs/agent57/lib/python3.7/site-packages/rl/callbacks.py", line 11, in <module>
    from keras.callbacks import Callback as KerasCallback, CallbackList as KerasCallbackList
ImportError: cannot import name 'CallbackList' from 'keras.callbacks' (/home/initial/miniconda3/envs/agent57/lib/python3.7/site-packages/keras/callbacks.py)

Any idea about why this is happening ?
Thanks!

**Comment by pocokhc** [comment]
The import error seems to be happening in keras-rl(import rl.core).
What is the version of keras-rl?

```
$ pip list | grep keras
keras-rl                           0.4.2
```

Or try keras-rl latest and try it.

```
$ pip install --upgrade keras-rl
```

I hope it helps you.

**Comment by Gaethje** [comment]
Thank you for the reply.
I solved the problem - adding this line in tensorflow callback directory init
from tensorflow.python.keras.callbacks import CallbackList
Great repository! Thanks.
