### ISSUE TITLE
「embedding network」について

### ISSUE THREAD

**Issue by tokin19** [pocokhc/agent57#5]
最近、agent57の学習を始めました。
qiitaの記事、とても参考にしています。ありがとございます。

「embedding network」について質問です。

embedding networkは、論文に記述がなかったように思いますが、
実装をする際、どの文献を参考にしたのでしょうか。
(記述があったらすいません)

また、そもそも、埋め込み関数のメリットがまだ、よくわかっていません。
何か、いい文献を知っていましたら教えてください。

よろしくお願いします。

**Comment by pocokhc** [comment]
参考にしていただきありがとうございます。

embedding networkについてはNGUの論文( https://openreview.net/forum?id=Sye57xStvB )を参考にしています。
(２章の真ん中あたりに太字項目で説明があります)

embedding networkはNGUが初出だと思います。
導入の経緯に関しては論文内の記述をざっくりいうと、
1. 環境はアクションに関係なくいろいろ変化する
2. アクションに関係ない環境の変化をとりいれるとうまく探索できない
3. アクションに関係ある環境の変化だけを学習に取り入れたい
→エピソード記憶部（embedding networkを含む）を導入
みたいな感じで書いてあります。

＞また、そもそも、埋め込み関数のメリットがまだ、よくわかっていません。
論文以上のことは私も分かりません。
話しの流れ的に、アクションに関係ある環境の変化だけを学習している部分が embedding network になると思います。
（埋め込み関数に関してはたしかあまりはっきり役割に関しては書かれていなかった記憶があるんですよね…）

以上、よろしくお願いします。

**Comment by tokin19** [comment]
コメントありがとうございます！
論文と要約を教えていただき、ありがとうございます。
詳しく調べてみます！
