### ISSUE TITLE
「RDN」について質問です

### ISSUE THREAD

**Issue by tokin19** [pocokhc/agent57#6]
Qiitaの中で、RNDについての記事があると思います。
コードを作成する際は、次の論文のAlgorithm 1(ページ14)を参考にして作成されましたか？

**Comment by pocokhc** [comment]
次の論文が何か分かりませんが…
[NGUの論文](https://openreview.net/forum?id=Sye57xStvB)のAlgorithm 1はエピソード記憶部の計算しか書いておらずRNDでは参考にしていません。

RNDの計算部分に関しては、２章の "Integrating life-long curiosity" に書いてあります。
それ以外は[Qiita記事](https://qiita.com/pocokhc/items/8684c6c96d3d2963e284#%E7%94%9F%E6%B6%AF%E8%A8%98%E6%86%B6%E9%83%A8life-long-novelty-module-1)に書いてある通りです。

**Comment by tokin19** [comment]
＞NGUの論文のAlgorithm 1はエピソード記憶部の計算しか書いておらずRNDでは参考にしていません。
教えていただき、ありがとうございます。 

論文を記載せず、大変に、申し訳ありませんでした。
次の論文のことを指しています。
https://arxiv.org/pdf/1810.12894.pdf
